### PR TITLE
Open base in craft of exile

### PR DESCRIPTION
**Pull request by lebster**
This needs some work but I thought it would be nice to open the base in craftofexile. Eventually maybe influences etc if the item already has it.

### CODE REVIEW

**Comment by SnosMe** [comment]
Thank you for interest.

What is the purpose of including `bi` parameter

**Comment by lebster** [comment]
That is fine, I will keep updating this for my own use for now. Let me know if you need me to change anything to make it acceptable.

**Comment by SnosMe** [comment]
The blocking thing here is addition/maintaining of `coeBaseIds.json` and `coeBaseInfo.json`.
poe.ninja items has URL-safe `detailsId`, I propose do same on CoE.

So "Vaal Regalia" has id `vaal-regalia`.
And base items with variants:
Two-Toned Boots: `two-toned-boots-ar-es`, `two-toned-boots-ar-ev`, `two-toned-boots-ev-es`.
Two-Stone Ring: `two-stone-ring-fire-cold`, `two-stone-ring-cold-lightning`, `two-stone-ring-fire-lightning`.

nebuchenazarr\#4600

**Comment by SnosMe** [comment]
Needs to be refactored to `https://www.craftofexile.com/?eimport=` that accepts plain Ctrl+C 

also hide hotkey in settings when language is not English

**Comment by lebster** [comment]
Branch has been refactored and squashed to use eimport.

**Comment by odt1** [comment]
bug: doesn't work on white and blue items

**Comment by SnosMe** [comment]
@odt1  Can you give Ctrl+C of white item?

**Comment by lebster** [comment]
@SnosMe I validate that there is a baseType before opening crafotofexile. It looks like all white/blue gear is not returning a baseType from parseClipboard.

**Comment by lebster** [comment]
`Rarity: Normal
Vaal Axe
--------
Two Handed Axe
Physical Damage: 104-174
Critical Strike Chance: 5.00%
Attacks per Second: 1.15
Weapon Range: 13
--------
Requirements:
Level: 64
Str: 158
Dex: 76
--------
Sockets: R 
--------
Item Level: 82
--------
25% chance to Maim on Hit (implicit)
--------
Redeemer Item
`


`Rarity: Normal
Destroyer Regalia
--------
Energy Shield: 104
--------
Requirements:
Level: 53
Int: 144
--------
Sockets: B-G B-B B-B 
--------
Item Level: 84
`


`Rarity: Magic
Stout Saint's Hauberk
--------
Armour: 443
Energy Shield: 73
--------
Requirements:
Level: 67
Str: 109
Int: 94
--------
Sockets: R R-R-B B-R 
--------
Item Level: 84
--------
+42 to maximum Life
`

**Comment by lebster** [comment]
@odt1 It should work with blue/white items now.

**Comment by odt1** [comment]
Everything seems to be working properly now, love this feature, been using it for at least 2 weeks, huge thanks. 
Only other issue i've encoutered is "two-stone rings" bases do not open in CoE with eimport, but thats purely CoE site problem. 

@SnosMe merge as beta-feature possible?

**Comment by SnosMe** [comment]
@odt1 will merge when I'm done improving my data generation pipeline 😄 not it takes all time, so it looks like APT is not in development at all 😄

**Pull request merged**
