### PR TITLE
Allow scanning of heist contracts and blueprints via map scanner

### LINKED ISSUE #241: Danger contracts modifiers
Can we have this ability please? Well essentially it would be similar to checking map modifiers.

Example input of contract:

```
Rarity: Rare
Oblivion Oath
Contract: Smuggler's Den
--------
Client: Marcine Clavus
Heist Target: Enigmatic Assembly A4
Area Level: 81
Requires Trap Disarmament (Level 1)
Item Quantity: +65% (augmented)
Item Rarity: +39% (augmented)
Alert Level Reduction: +31% (augmented)
Time Before Lockdown: +21% (augmented)
Maximum Alive Reinforcements: +31% (augmented)
--------
Requirements:
Level: 62
--------
Item Level: 81
--------
Players are Cursed with Vulnerability, with 60% increased Effect
Guards deal 27% increased Damage
21% increased time before Lockdown
Lockdown occurs immediately when Alert Level is full
Reward Rooms have 15% increased Monsters
Players have 25% less Area of Effect
--------
"I currently possess four-hundred and forty-four pieces of this ancient
and puzzling device. A few seem to be missing. This part is crucial."
--------
Give this Contract to Adiyah in the Rogue Harbour to embark on the Heist.
```

### PR DESCRIPTION
**Pull request by secondfry**
This will close #241.

### CODE REVIEW

**Comment by secondfry** [comment]
image
image

**Comment by danthespal** [comment]
is not working anymore

**Comment by danthespal** [comment]
is not working anymore

**Comment by SnosMe** [comment]
e765f4620870a25c1f6d6daabebb025b96c84a54

**Pull request closed without merging**
